iii

diff --git a/7loop b/7loop
--- a/7loop
+++ b/7loop
@@ -1,30 +1,40 @@
 #!/bin/bash
+
+USERID=$(id -u)
 R="\e[31m"
 G="\e[32m"
 N="\e[0m"
-Y="\e[30m"
 
-userid=$(id -u)
-
-if [ $userid -ne 0 ]
-   then
-       echo -e "$R your not in root user $N"
-       exit 1
-    else
-       echo -e "$Y your are in root user....... $N"
-fi
-
-for package in $@
-  do
-    dnf install $package
-    if [ $userid -ne 0 ]
-      then
-          echo -e "$R not installed $package........... $N"
-          exit1
-        else
-           echo -e "$G $package installed completed........ $N"
+CHECK_ROOT(){
+    if [ $USERID -ne 0 ]
+    then
+        echo "Please run this script with root priveleges"
+        exit 1
     fi
-done    
+}
 
-      
+VALIDATE(){
+    if [ $1 -ne 0 ]
+    then
+        echo -e "$2 is...$R FAILED $N"
+        exit 1
+    else
+        echo -e "$2 is... $G SUCCESS $N"
+    fi
+}
 
+CHECK_ROOT
+
+# sh 15-loops.sh git mysql postfix nginx
+for package in $@ # $@ refers to all arguments passed to it
+do
+    dnf list installed $package
+    if [ $? -ne 0 ]
+    then
+        echo "$package is not installed, going to install it.."
+        dnf install $package -y
+        VALIDATE $? "Installing $package"
+    else
+        echo "$package is already installed..nothing to do"
+    fi
+done
