qqq

diff --git a/7loop b/7loop
--- a/7loop
+++ b/7loop
@@ -1,5 +1,13 @@
 #!/bin/bash
-
+VALIDATE(){
+    if [ $1 -ne 0 ]
+    then
+        echo -e "$2 is...$R FAILED $N"
+        exit 1
+    else
+        echo -e "$2 is... $G SUCCESS $N"
+    fi
+}
 
 for package in $@ # $@ refers to all arguments passed to it
 do
